version: '3'

services:
  sever:
    image: "videochat"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8080:8080"
    command:  --addr :8080
     